server:
  port: 8080

elasticsearch:
  host: 127.0.0.1
  port: 9200

spring:
  datasource:
    url: jdbc:mysql://x.x.x.x:3306/poem?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: xxx
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    suffix: .html